behaviors:
  
  PlayerX:
    trainer_type: poca
    hyperparameters:
      batch_size: 64
      buffer_size: 4096
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.25
      lambd: 0.99
      num_epoch: 10
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 8
      vis_encode_type: simple
      goal_conditioning_type: none
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.80
        strength: 1.0
    keep_checkpoints: 30
    checkpoint_interval: 10000
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 2000
    threaded: false
    self_play:
      window: 20
      play_against_latest_model_ratio: 0.5
      save_steps: 1000
      swap_steps: 2000
      team_change: 10000
  
  PlayerY:
    trainer_type: poca
    hyperparameters:
      batch_size: 32
      buffer_size: 1028
      learning_rate: 0.0003
      beta: 0.02
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 10
      learning_rate_schedule: constant
      beta_schedule: constant
      epsilon_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 6
      vis_encode_type: simple
      goal_conditioning_type: none
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.80
        strength: 1.0
    keep_checkpoints: 30
    checkpoint_interval: 10000
    max_steps: 450000
    time_horizon: 64
    summary_freq: 500
    threaded: false
    self_play:
      window: 5
      play_against_latest_model_ratio: 0.5
      save_steps: 1000
      swap_steps: 2000
      team_change: 10000