behaviors:

  PlayerX:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 512
      learning_rate: 3e-4
      beta: 0.01
      epsilon: 0.3
      lambd: 0.99
      num_epoch: 7
      learning_rate_schedule: constant
    checkpoint_interval: 100000
    network_settings:
      normalize: True
      hidden_units: 32
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: True
          hidden_units: 8
          num_layers: 2
          deterministic: True
    keep_checkpoints: 20
    max_steps: 10000000
    time_horizon: 32
    summary_freq: 1000
    threaded: true
    self_play:
      save_steps: 10000
      team_change: 20000
      swap_steps: 2000
      window: 40
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0

  PlayerY:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32
      buffer_size: 512
      learning_rate: 3e-4
      epsilon: 0.3
      lambd: 0.99
      num_epoch: 7
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 32
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 32
    summary_freq: 1000
    threaded: true
    self_play:
      save_steps: 10000
      team_change: 20000
      swap_steps: 2000
      window: 40
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0