behaviors:

  Analog Player:
    trainer_type: ppo
    summary_freq: 10000
    time_horizon: 128
    max_steps: 10000000
    keep_checkpoints: 10
    checkpoint_interval: 1000000
    threaded: false
    hyperparameters:
      learning_rate: 3e-4
      batch_size: 512
      buffer_size: 4096
      learning_rate_schedule: linear
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
    network_settings:
      hidden_units: 32
      num_layers: 1
      normalize: false
      vis_encode_type: simple
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
    self_play:
      save_steps: 20000
      team_change: 100000
      swap_steps: 10000
      play_against_latest_model_ratio: 0.5
      window: 15
      initial_elo: 0.0